name: Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginx

jobs:
  build-and-push:
    # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/concepts/security/github_token?utm_source=chatgpt.com#about-the-github_token
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
    permissions:
      #contents: read
      packages: write

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v7

      - name: Login to GHCR
        # https://github.com/docker/login-action#github-container-registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        # https://github.com/docker/build-push-action#path-context
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

